proxies:
p: &p
  type: http
  interval: 1800
  health-check:
    enable: true
    url: http://www.gstatic.com/generate_204
    interval: 300
 
proxy-providers:
  机场1:
    <<: *p
    url: "订阅链接"
    path: ./proxy_providers/qcjs.yaml
 
 
proxy-groups:
  - name: 代理设置
    type: select
    proxies:
      - 机场1
      - 关闭代理

  - name: 机场1
    type: select
    use:
      - 机场1

  - name: 关闭代理
    type: select
    proxies:
      - DIRECT